version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    container_name: nodejs_app
    profiles: [nodejs_app]
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/greeting"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
